site_name: Stab
site_desc: 'Stab: Start Blogging w/ Simple static blog generator'
site_baseurl: /usr/stab

author: oxalorg

# Default values
default_layout: post
allowed:
    - .md
    - .mkd
    - .markdown
ignored:
    - README.md
